[package]
name = "lapin-futures"
version = "0.12.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
nom = "^4.0"
log = "^0.4"
bytes = "^0.4"
futures = "^0.1"
futures-locks = { git = "https://github.com/asomers/futures-locks.git" }
tokio-codec = "^0.1"
tokio-io = "^0.1"
tokio-timer = "^0.2"
lapin-async = {version = "^0.12", path = "../async"}
cookie-factory = "^0.2"
amq-protocol = "^0.21"

[dev-dependencies]
env_logger = "^0.5"
tokio = "^0.1.7"
